### ISSUE TITLE
An error occurs when 渋谷区ハチ公バス GTFS-JP data is used

### ISSUE THREAD

**Issue by lapinrose0101** [MaaSee/HARoSE#13]
@takoyaki-3  @kazuhiro-takaya 
An error occurs when 渋谷区ハチ公バス GTFS-JP data is used. Is there any solution for this problem?

- GTFS
  - 渋谷区ハチ公バス
  - Resources
    - https://www.city.shibuya.tokyo.jp/assets/mng/131130_gtfs-jp_hachiko_bus.zip
- OSM
  - [kanto-latest.osm.pbf](https://download.geofabrik.de/asia/japan/)
- Error logs
```
> go run ./server.go
go: downloading github.com/takoyaki-3/go-routing-interface v0.0.7
start server.
not found !
2022/06/02 14:02:40 http: panic serving [::1]:33284: runtime error: index out of range [-1] 
goroutine 9 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go-1.18/src/net/http/server.go:1825 +0xbf
panic({0x83ca40, 0xc0003f2120})
        /usr/lib/go-1.18/src/runtime/panic.go:844 +0x258
github.com/takoyaki-3/go-routing-interface.(*TripStr).AddProperty(0xc0007237c0, 0xc000010018?)
        /home/val00274/go/pkg/mod/github.com/takoyaki-3/go-routing-interface@v0.0.7/addProperty.go:169 +0x28d
main.main.func2({0x90d378?, 0xc0003fa0e0}, 0x0?)
        /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/1acb04963de44a6406d1b21cb90baa6f931d4dc0a2a9802d63652bb2270934cc/exec/server.go:96 +0x6c5
net/http.HandlerFunc.ServeHTTP(0x7f7a6853e598?, {0x90d378?, 0xc0003fa0e0?}, 0x4129a5?)      
        /usr/lib/go-1.18/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000710015?, {0x90d378, 0xc0003fa0e0}, 0xc0003fe100)       
        /usr/lib/go-1.18/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000407410?}, {0x90d378, 0xc0003fa0e0}, 0xc0003fe100)   
        /usr/lib/go-1.18/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000a6280, {0x90d6c0, 0xc000407320})
        /usr/lib/go-1.18/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/lib/go-1.18/src/net/http/server.go:3071 +0x4db
```

**Comment by kazuhiro-takaya** [comment]
![image](https://user-images.githubusercontent.com/87961198/172998161-3e562174-eb3f-4e0e-8902-c874f6d266b7.png
上記入力画面にて、「ダイヤ」の欄に`20220415`を入力すると経路が見つかり、エラーは出ませんでした

**Comment by kazuhiro-takaya** [comment]
「ダイヤ」欄のデフォルト値（私の環境では`20210215`）では経路が見つからずエラーに。
GTFSの`calendar.txt`と`conf.json`で指定する日付（`start_date`および`end_date`）の範囲に注意が必要

**Comment by kazuhiro-takaya** [comment]
エラーログの5行目
```
2022/06/02 14:02:40 http: panic serving [::1]:33284: runtime error: index out of range [-1] 
```
以降は[#8](https://github.com/MaaSee/HARoSE/issues/8)で対応すべき事項

**Comment by lapinrose0101** [comment]
@kazuhiro-takaya 
LGTM!

**Comment by lapinrose0101** [comment]
fixed #14
