### ISSUE TITLE
到達圏検索 パラメータ指定でdestinationを外すとエラー

### ISSUE THREAD

**Issue by kazuhiro-takaya** [MaaSee/HARoSE#18]
表題の通り。
readmeにあるように、以下を叩くと到達圏を検索できる。
```
GET http://localhost:8000/routing_surface?json={"origin":{"time":28800,"lat":35.67468284259795,"lon":139.7613707236869},"destination":{"time":32400,"lat":34.39101899572567,"lon":132.45094923488853},"json_only":true,"properties":{"timetable":"20220715"}}
````

readmeの説明ではdestinationは不要だが、以下のようにdestinationをパラメータから除外してAPIを叩くとエラーになる。
```
GET http://localhost:8000/routing_surface?json={"origin":{"time":28800,"lat":35.67468284259795,"lon":139.7613707236869},"json_only":true,"properties":{"timetable":"20220715"}}
```
エラーメッセージ
```
2022/08/22 17:01:56 http: panic serving 127.0.0.1:45184: runtime error: invalid memory address or nil pointer dereference
goroutine 38 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x7fc0c0, 0xb51d30})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/takoyaki-3/go-routing-interface.FindNearestNode({0x0?, 0x0?, 0x0?, 0x0?}, 0x1?)
        /home/kazuhiro/go/pkg/mod/github.com/takoyaki-3/go-routing-interface@v0.0.7/input.go:47 +0x17d
main.GetQuery(0xf?, 0xc000082670?)
        /home/kazuhiro/HARoSE/exec/server.go:207 +0xab
main.main.func3({0x90e7b8?, 0xc03ee42000}, 0x0?)
        /home/kazuhiro/HARoSE/exec/server.go:145 +0x59
net/http.HandlerFunc.ServeHTTP(0x7ffa654b7598?, {0x90e7b8?, 0xc03ee42000?}, 0x4129a5?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0258bec55?, {0x90e7b8, 0xc03ee42000}, 0xc0d80c6000)
        /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0d9b46180?}, {0x90e7b8, 0xc03ee42000}, 0xc0d80c6000)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000be280, {0x90eb00, 0xc0d7fe3ad0})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by lapinrose0101** [comment]
@kazuhiro-takaya 
フロントエンドがないので、引数からdestinationを外したいという修正を実施ください

**Comment by kazuhiro-takaya** [comment]
修正完了
